import { ApolloWrapper } from "@/components/ApolloWrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Raccoons App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ApolloWrapper>
        <div style={{ display: "flex", gap: "1em", alignItems: "center", borderBottom: "solid 1px black" }}>
          <h2>Nav - </h2>
          <Link href="/">Home</Link>
          <Link href="/characters">Characters</Link>
          <Link href="/countries">Countries</Link>
        </div>
        {children}
      </ApolloWrapper>
      </body>
    </html>
  );
}
